from join.exceptions import JoinException


class JoinCoreError(JoinException):
    pass
